---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# Common roles for preparing the image
- name: Check inputs, prepare logs, hostname, install basic dependencies and AWS Data Provider
  become: true
  hosts: all
  roles:
    - role: check-inputs
      vars:
        input_variables_to_check: 
          - EC2_HOSTNAME
          - PRIVATE_DNS_ZONE
          - MASTER_PASSWORD
          - HANA_SID
          - HANA_INSTANCE_NUMBER
          - S3_BUCKET_MEDIA_FILES
          - AWS_CLI_PROFILE
    - role: common-os-tasks-dr
    - role: prepare-logs-folders-dr
    - role: install-pkg-mgr-dependencies-dr
    - role: install-aws-sap-data-provider-dr
    - role: set-hostname-dr

# Installation-specific roles
- name: Set parameters and mount disks
  become: true
  hosts: all
  roles:
    - role: ansible-role-disks
    - role: ansible-role-parameters

# RedHat official roles for preparing for SAP Installation
- name: Prepare host with RedHat certified roles
  become: true
  hosts: all
  roles:
    - role: sap-preconfigure
      vars:
        sap_preconfigure_selinux_state: disabled
        sap_preconfigure_fail_if_reboot_required: false
    - role: sap-hana-preconfigure
      vars:
        sap_hana_preconfigure_fail_if_reboot_required: false

# Hana installation roles
- name: Download and Install Hana
  become: true
  hosts: all
  roles:
    - role: ansible-role-download-and-install
