---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Create the disk mapping file
  include_tasks: create_disk_mapping_file.yml
  
- name: Mount disks Oracle 
  include_tasks: mount_disk_oracle.yml
  
- name: Mount disks Oracle SAP
  include_tasks: mount_disk_oracle_sid.yml
  
  
- name: Mount disks Oracle Data
  include_tasks: mount_disk_oracle_data.yml

- name: Mount disks Oracle Logs
  include_tasks: mount_disk_oracle_logs.yml

- name: Mount disks Oracle orarch
  include_tasks: mount_disk_oracle_orarch.yml

- name: Mount shared EFS SAPMNT
  include_tasks: mount_disk_sapmnt.yml

- name: Mount disks for Swap
  include_tasks: check_swap_enabled.yml

- name: Reboot instance
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
